import type { Metadata } from "next";
import { CaptainAuthProvider } from "./captain-auth-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "{name}",
  description: "Generated by CAPTAIN",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="{defaultLocale}">
      <body>
        <CaptainAuthProvider>{children}</CaptainAuthProvider>
      </body>
    </html>
  );
}
