import type { Metadata } from "next";
import { CaptainConvexProvider } from "@/integrations/convex/captain-convex-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "{name}",
  description: "Generated by CAPTAIN",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="{defaultLocale}">
      <body><CaptainConvexProvider>{children}</CaptainConvexProvider></body>
    </html>
  );
}
